version: "2.4"

networks:
  default:
    external:
      name: nginx-proxy

services:
  homeadguard:
    hostname: homeadguard
    container_name: homeadguard
    build:
      context: .
      dockerfile: Dockerfile
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp" # DNS
      - "8053:80/tcp" # Web Interface
    volumes:
      - './data:/opt/adguardhome/work/data'
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
      - 208.67.222.222
      - 9.9.9.10
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=dns.woki.com
      - VIRTUAL_PORT=80
